/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SchimmelsZwammenHuiszwamRouteImport } from './routes/schimmels-zwammen.huiszwam'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SchimmelsZwammenHuiszwamRoute =
  SchimmelsZwammenHuiszwamRouteImport.update({
    id: '/schimmels-zwammen/huiszwam',
    path: '/schimmels-zwammen/huiszwam',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/schimmels-zwammen/huiszwam': typeof SchimmelsZwammenHuiszwamRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/schimmels-zwammen/huiszwam': typeof SchimmelsZwammenHuiszwamRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/schimmels-zwammen/huiszwam': typeof SchimmelsZwammenHuiszwamRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/schimmels-zwammen/huiszwam'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/schimmels-zwammen/huiszwam'
  id: '__root__' | '/' | '/schimmels-zwammen/huiszwam'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SchimmelsZwammenHuiszwamRoute: typeof SchimmelsZwammenHuiszwamRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schimmels-zwammen/huiszwam': {
      id: '/schimmels-zwammen/huiszwam'
      path: '/schimmels-zwammen/huiszwam'
      fullPath: '/schimmels-zwammen/huiszwam'
      preLoaderRoute: typeof SchimmelsZwammenHuiszwamRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SchimmelsZwammenHuiszwamRoute: SchimmelsZwammenHuiszwamRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
